### ISSUE TITLE
Document libraries

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#135]
These are the files that got Fabrik into trouble with the JED. The original install copied the fabrik versions to the libraries/src/Document path, overwriting the ones that ship with J!. The changes Henk made to not move files (the movefiles function didn't actually move then, simply copied them) now copies the files from our component path to libraries/fabrik/Document. Unfortunately this does not do us any good as those who use these files are using Joomla\CMS\Document\Document and as a result never find our version of it. 

This is the back and forth that went on between the J! people and Fabrik people (at least part of it), there was no way to override the Document functions and J! would not agree to provide a way, so Fabrik overwrote the actual files.

I am afraid we might have to do the same thing.

**Comment by skurvish** [comment]
I wonder if it might be possible to override the class itself using the techniques used by the MVC Overrride. Basically in our system plugin we would do the following:

Read in the classes, modify the class names with a suffix of Default (or something else), then import this class into the J! PHP namespace, the import or overrides and have our classnames extend the original classname with the default suffix. 

I think this might work. If so then we might be able to get relisted on the JED.

Thoughts?

**Comment by trob** [comment]
`The original install copied the fabrik versions to the libraries/src/Document path, overwriting the ones that ship with J!.` No, it only added some new ones (Pdf, partial). One real issue was that others did the same (which - as far as I know were not banned) and so the last Pdf component installed was overriding the predecessor.

Not sure what you mean with 
Unfortunately this does not do us any good?
The PDFs are working with Henk's aliases and  files in libraries/fabrik/Document

**Comment by skurvish** [comment]
Ah, I see the problem. The 2 document files from Fabrik were still in my libraries/src/Document directory so were being picked up instead of the ones in our library. These 2 files did not ship with J! so they belong only to us. I deleted them from my J! library and all is fine now (other than other stuff in Fabrik I need to fix).

Closing.
