### ISSUE TITLE
Fabrik 4.0 does not work on Joomla 4.2

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#227]
Just updated to J!4.2 and fabrik does not work anymore. It looks like they changed the toolbar, because it's gone.
So let's stay on J!4.1.5 for a while. We have to solve this some time.

**Comment by trob** [comment]
UpgradeThere was an issue for a few with some updates to 4.2.0 We have removed the update while we can investigate the issue.....Better you are not the 1st one installing the updates😉Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: joomlahenk ***@***.***> Datum: 17.08.22  09:34  (GMT+01:00) An: joomlahenk/fabrik ***@***.***> Cc: Subscribed ***@***.***> Betreff: [joomlahenk/fabrik] Fabrik 4.0 does not work on Joomla 4.2 (Issue
  #227) 
Just updated to J!4.2 and fabrik does not work anymore. It looks like they changed the toolbar, because it's gone.
So let's stay on J!4.1.5 for a while. We have to solve this some time.

**Comment by skurvish** [comment]
4.2.1 should fix this issue when it is released.

**Comment by joomlahenk** [comment]
Yes, on discord @sadaf3d reported a successful fabrik4 install on J!4.2.1. So I close this issue.

**Comment by joomlahenk** [comment]
In J!4.2.2 I get Call to undefined method Joomla\CMS\Form\Field\MenuField::getDatabase(), because in libraries/src/Form/Field/MenuField.php:49, $db = Factory::getDbo(); they changed it to $db = $this->getDatabase();
This is a J!4.2.2  bug. I created an issue for that, but I think they will not take that serious (as usual). 
We make a call to this in administrator/components/com_fabrik/classes/FormField.php:468. Maybe we can bypass j! core??

**Comment by joomlahenk** [comment]
I close this one. See issue #259
