### ISSUE TITLE
Installer: also install mootools

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#26]
mootools need to be installed in media\system\js\

**Comment by trob** [comment]
Better install it "inside" Fabrik so that Fabrik can run it's own version. E.g. it needs fixes/hacks for Googlemaps (see https://fabrikar.com/forums/index.php?threads/google-maps-element.52933/page-2#post-278994).

And Joomla doesn't like components installing anything in Joomla folders (that's why Fabrik was banned from the J! extensions).

**Comment by skurvish** [comment]
Given the mods mention then we cannot include mootools from CDN then. Fabrik has traditionally included copies of such libraries rather than point to a CDN. I assume this is to eliminate breakages when a library has been updated in the CDN. This does however mean that libraries will need to be updated from time to time.

**Comment by trob** [comment]
Document stuff seems to be tricky. As far as I know Hugh was struggling to get the PDF out of there (because this was the J! extension reason) but did't get it done.

`mootools from CDN` Do they have a recent version at all?

**Comment by joomlahenk** [comment]
mootools did not change since very long as I have understood. This is also one of reasons why J! stopped using it. In fact: they prefer vanilla JS. I gladly would get rid of mootools too (and even jquery), but then we have to convert. Anybodies hobby?

**Comment by skurvish** [comment]
I too would like to get rid of mootools and move to vanilla JS but I think this is a task way too bid for us to tackle right now. I do hove some experience converting from jQuery to vanilla javascript but I have no experience whatsoever using mootools. If we find we have troubles with the existing JS then we may need some help in this area.
