### ISSUE TITLE
php8 and/or J!3/J!4 backward comp issues

### ISSUE THREAD

**Issue by trob** [joomlahenk/fabrik#304]
Just to keep in mind

- In J!3 loadResult() (of Select COUNT(*) ) returns a string, in J!4 an int (so `if ($result === '0')` must become `if ($result === 0)` )
- in php8 ''<>0

to be continued

**Comment by joomlahenk** [comment]
If you use: if ($result === '0') that means that $result must be a string because you use === instead of ==
So you could also use if ($result == '0'). In that case PHP will interpret '0' (string) the same as 0 (int)
if ($result === 0) is always better to use, because count indeed does return an int.
See also https://stackoverflow.com/questions/80646/how-do-the-php-equality-double-equals-and-identity-triple-equals-comp

**Comment by joomlahenk** [comment]
So it's not a php8 and/or J!3/J!4 backward comp issue, but the correct use of the php comparison operator in fabrik.

**Comment by trob** [comment]
No. 
In J!3 the result of ...COUNT(*)... IS a string, so ==='0' is correct in F3.
In J!4 the result is INT so you have to use ===0 in F4

In php8 ''<>0 because now it's casting 0 to string, so you'll have ''<>'0' whereas php7 did it the other way around
https://www.php.net/manual/en/migration80.incompatible.php
https://fabrikar.com/forums/index.php?threads/form-email-plugin-doesnt-send-mails-in-php8.53466/#post-279458

So there may be other comparisions poping up...

**Comment by trob** [comment]
Maybe J!3 DB driver is casting it to string?  (var_dump is showing string here) Anyway, we now handle INTs in F4...

**Comment by skurvish** [comment]
Not sure either place is a good place to keep a running commentary on the issues. I think it is best if we open a new issue each time we come across them, then we can fix them as we go along.

**Comment by skurvish** [comment]
Closing, we should open separate issues as we find them. It will be easier to track and fix that way.
