### ISSUE TITLE
[alpha2] issue - create new list details tab disappears

### ISSUE THREAD

**Issue by raramuridesign** [joomlahenk/fabrik#349]
Step 1 - create new list
Step 2 - Click on any tab on the left side, and the details tab on the left disappears
Step 3 - reload, click a tab on the right side and then the left and the details tab stays

![image](https://user-images.githubusercontent.com/902376/196040143-3229c9f8-a736-4589-94a6-d0534c0ae9bf.png)

When clicking on data tab, details tab goes

![image](https://user-images.githubusercontent.com/902376/196040204-9f84e570-aaa9-4b40-9c31-8f3d946c9d38.png)

**Comment by raramuridesign** [comment]
This also happens when creating a **Group**.
Click on any tab on the left and the first tab disappears. 
Continue clicking on the other buttons on the left and they eventually all disappear.

**Comment by skurvish** [comment]
I have seen this before but I thought it was resolved, guess not.

**Comment by joomlahenk** [comment]
I don't have this issue.

**Comment by skurvish** [comment]
Mathew, did you clear your cache?

**Comment by skurvish** [comment]
Still happening on my system. I will have a look.

**Comment by skurvish** [comment]
Seems to happen when one of the items is clicked before Fabrik has fully loaded. I can fix it in javascript by forcing the display back to block once fabrik is fully loaded but the user will see the item disappear momentarily then reappear again.

I tried to place a mutation observer on the item but it doesn't exist in the dom when domContentLoaded is run, so I have no idea who is hiding it.

Is it acceptable to have the momentary item hidden then reappear? I think it will take someone far more versed in javascript etc to find the root cause than I am.

**Comment by raramuridesign** [comment]
@skurvish Yes, I think that would be fine - might be worth marking this to revisit at a later stage if this is an issue for users.
But your solution is good for now.

**Comment by joomlahenk** [comment]
This may have something to do with the sticky spinner #371. The spinner is meant to prevent to click an item before Fabrik has fully loaded.

**Comment by skurvish** [comment]
Where do we usually see this sticky spinner? I remember seeing it and when you try to click on something it tells you that Fabrik is not yet fully loaded and to wait. I don't remember where I saw that though.

**Comment by trob** [comment]
https://github.com/joomlahenk/fabrik/issues/371
These won't stop at any time, I don't think these spinners are loading indicators, they just don't get a display:none or so after a selection is done.

**Comment by skurvish** [comment]
Hack fix for hiding sidebar menu items in PR #378
