### ISSUE TITLE
[alpha2] admin form - error with time_date

### ISSUE THREAD

**Issue by raramuridesign** [joomlahenk/fabrik#353]
See screen shot for clarification

![image](https://user-images.githubusercontent.com/902376/196041527-6e3133a8-b07c-464c-aa6f-c609c165346c.png)

**Comment by trob** [comment]
Is this a date or jdate element?

**Comment by raramuridesign** [comment]
@trob It is `date` element

**Comment by raramuridesign** [comment]
Admin form, meaning in the backend or joomla(fabrik) admin area.

**Comment by trob** [comment]
Issue replicatable.
Only in the backend, independend of any special element, just coming with any failed validation.

In alpha2 it's reclaiming "incorrect date_time...."

On my GitHub site I get "Field 'last_page' doesn't have a default value" in the backend on every form with a validation error.
I don't see what is going on there.
Maybe some "old" error messages popping up with failed validations in the backend?
Depending on J!4.3.2? Because we didn't see (or at least realized) this before, but I get this error also if I reset my GitHub version to somewhere in August.



> Admin form, meaning in the backend or joomla(fabrik) admin area.
Ah, ok. We use "Admin form" for the forms to handle Fabrik (lists, elements etc).

**Comment by skurvish** [comment]
I can recreate this as well. I will have a look.

**Comment by skurvish** [comment]
Fixed in PR #362 

You won't see this fixed with an install over top of an existing alpha install. You will need to use phpmyadmin or similar to execute the following command:

ALTER TABLE `#__fabrik_form_sessions` MODIFY `time_date` datetime DEFAULT null;

Depending on what you use you may have to insert the db prefix. Once you do this the error should go away.

**Comment by skurvish** [comment]
Note, anyone installing F4 the first time on  virgin version of J! or as part of an upgrade from J3 will not have this issue now.

**Comment by trob** [comment]
It's ok with this DB modification (also on my GitHub site where the default for last_page was missing).
I don't know why Fabrik stores to form_session in case of a failed validation in the backend, but it's the same in F3, so...

**Comment by skurvish** [comment]
I think it is to handle multipage forms where the validation failure might happen later than the first page. Just a guess though.
