### ISSUE TITLE
The preview on the content type page keeps loading and has a sticky spinner.

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#373]
After creating a new list, the content type page opens. On the content type page the preview keeps loading and has a sticky spinner.
Saw this some time ago already, but I didn't report yet. There was a time the preview loaded, but it still had the spinner.
I can just save & close to create a new list, but really using content type and changing it can not be done this way.

**Comment by trob** [comment]
It's working on my GitHub site,  on the alpha2 site it's working if I select Default(old date) or Events.

But I have the old date element published.

I assume it's "loading" if one of the used elements is missing. If I select Contact us and then save anyway it's complaining about the user element.

**Comment by trob** [comment]
It seems to be only "Contact us", all others are working on my alpha2 site (Event is showing " One or more of the element types used in this content type are not installed or are disabled: user, user").
Maybe the textarea element (editor) is breaking the preview?

**Comment by trob** [comment]
No, I have error reporting=none but it still fails with the "Contact us" content type (and only with this one).

**Comment by joomlahenk** [comment]
Indeed, if I set error reporting to none I have this issue only for the "Contact us". But once selected "Contact us" it keeps spinning for all others too. If this is caused by the the strftime deprecation warning, we keep having this problem until J! solves the deprecation. It's on their PR list, but no plans to solve it in J!4.x (see PR #38276)

**Comment by joomlahenk** [comment]
Strange that an ajax response can be prefixed by a deprecation warning. I think this should never be the case, but this is how it was created in Fabrik. I also don't understand why the content type page must be opened using ajax.

**Comment by skurvish** [comment]
When the user selects the content type, an ajax request is made to obtain the preview html. This html is returned in a json encoded packet. However, when error reporting is turned on php outputs the deprecated warning which is sent back to the requestor ahead of the json packet. Since the javascript that is parsing the response is expecting valid json it errors and basically does nothing, which includes not disabling the spinner.

I will have a look at why the Contact Us content type is not working.

**Comment by skurvish** [comment]
Fixed with PR #385 

The problem was that the Contacts us content type included a textarea element. Rendering a wysiwyg textarea element outputs modal markup and this gets sent as part of the ajax response but before the json encoded data. I had to check the response data for html ahead of the json data and if found insert it into the dom and the json parse the rest of the response.

I don't think that for this that it is absolutely necessary to insert the HTML into the DOM as the display is in preview mode so nothing is active and the modal will never pop up, however, I am going to leave it as is as there may be a case in the future where it is needed and it doesn't hurt anything.

Please test and if working close this issue.

**Comment by joomlahenk** [comment]
Is solved now.
