### ISSUE TITLE
Alter tables if exist

### ISSUE THREAD

**Issue by skurvish** [joomlahenk/fabrik#475]
Because we are doing updates to the tables with the F4 install, those elements that have their own tables but which had not been installed and used before are failing the F4 install because when we try and run the 4.0 update alter commands the table may not exist.

**Comment by skurvish** [comment]
PR #476 corrects this. We only alter the table if it exists.

**Comment by skurvish** [comment]
I am also going to remove the comments in the upgrade section about having to add these tables if they don't exist. Update sql not accounts for it.

**Comment by joomlahenk** [comment]
Maybe you can use the issue template to make it clearer.
Did you run into an issue when doing an upgrade ? 
Some time ago I changed the sql's and the xml for these plugins so that tables are created on install (and on upgrade). In J!3 the table is not created on install of the plugin while that should be done. The tables were created when used instead. In that case we get an issue on upgrade. 
As far as I know is that it worked well, but maybe something has changed in the meantime or I didn't test all conditions.
I now see that I forgot to remove the creation of tables in the php file, which may cause an issue now.
So I am curious how you discovered an issue with it. Or did you find this issue by code reviewing?

**Comment by joomlahenk** [comment]
What I am trying to explain in the wiki comments in the upgrade section is not to add the tables, but make sure they exist and if not then uninstall the plugin.
If, like in J!3, the table is not created on install of the plugin but created when used instead, then the table will not be uninstalled.

**Comment by skurvish** [comment]
I discovered the issue when I attempted to install alpha3 over top of my J3 to J4 upgrade. The installation failed because the table did not exists. It appears the table is not created on install of the plugin which is why there is code in the plugin php file to create it. As a result of it not being created the 4.0 upgrade sql file fails on the alter. You will also see in the comments plugin that there is code to add a column that was missed in the initial install.

I ran this on my J4 site after upgrade and it ran perfectly. The tables did not exist in my DB and no errors were reported on the upgrade.

**Comment by joomlahenk** [comment]
I did the same discovery and therefore added the sql in the xml to make it create the table on install. This should be the way, because only then the table will be uninstalled by Joomla.
I don't understand why it did not work for you, I will try again.

**Comment by joomlahenk** [comment]
First try:
Unknown column 'newsletter_engine' in 'j3upg_fabrik_change_log_fields'

**Comment by skurvish** [comment]
This column does not belong to the log plugin, it belongs to the consent plugin. Somehow got in there from the beginning of the 4.0.sql update file. PR #479 removes it.
