### ISSUE TITLE
Strange Editor behaviour in backend

### ISSUE THREAD

**Issue by wezetel** [joomlahenk/fabrik#481]
**To Reproduce**
1. Open a list (or form) definition and scroll down (with TinyMCE as Editor) until menu of intro editor disappeares
2. Push the Editor on/off button to show source code

**Expected behavior**
1. Intro textarea stays as it is
2. Full textarea can be used for coding

**Actual behavior**
1. Textarea is confused (screenshot 1)
2. Textarea is reduced to a small part of the screen and can't be extended with sizing handles (width only) (screenshot 2)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/18248764/199826214-3b794347-8972-4017-8e2c-749b484df2f2.png)
![grafik](https://user-images.githubusercontent.com/18248764/199827789-f61ebc2d-77b2-4f32-8d3f-bd11ab48d8e0.png)

**Additional context**
Similiar behaviour is observed with JCE,.

**Comment by trob** [comment]
Can be fixed by setting
`<div  class="controls">` in admin_bootstrap_control_group.php (for administrator\components\com_fabrik\views\list\tmpl
resp. bootstrap_control_group.php (for administrator\components\com_fabrik\views\form\tmpl

This is like it's done in other components but will extend all input and dropdowns to 100%.

Or it can be fixed by doing it like in 
administrator\components\com_fabrik\views\visualization\tmpl\bootstrap_control_group.php
by setting a width only for the editor fields, e.g.
`$style = $this->field->id == 'jform_intro' ? 'style="width:75%"': '' ?>
	<div <?php echo $style?>>`

**Comment by joomlahenk** [comment]
`<div class="controls">` Is an old class that was used in BS2. We removed it some time ago, because it conflicted with BS5.

**Comment by trob** [comment]
But it's used by J!4 GlobalConfig and also JCE and Akeeba configs, so...

**Comment by joomlahenk** [comment]
See https://getbootstrap.com/docs/3.4/migration/

**Comment by trob** [comment]
Ok.
But then Joomla is not really BS5. As I said 
`<div class="control-group">
	<div class="control-label"> ...</div>
	<div class="controls" >...</div>
</div>`
is used everywhere in the backend by Joomla and all other components.

Should be fixed with PR https://github.com/joomlahenk/fabrik/pull/482

**Comment by wezetel** [comment]
For me as simple webadmin the PR is working well and the issue is solved.
JCE and TinyMCE are behaving a little bit different on resizing the width of the field (wysiwyg or code mode), but this is something I assume is editor specific and doesn't really limit the use of fabrik.
Thanks for this solution!
