### ISSUE TITLE
Ajaxified form dropdown element ok status display

### ISSUE THREAD

**Issue by wezetel** [joomlahenk/fabrik#494]
**To Reproduce**
Create an ajaxified form with a dropdown element
Create a validation for this element

**Expected behavior**
Field turns green and eventually gets a green hook, if correct data is entered

**Actual behavior**
Green hook is only partial visible

**Screenshots**
![grafik](https://user-images.githubusercontent.com/18248764/200136084-c91b58c8-f2e7-4f70-8993-5bbb685014f0.png)

**Additional context**
No problem with green hook on simple elements

**Comment by skurvish** [comment]
Yes, the problem seems to be related to the BS5 form-select. The js code somewhere is inserting the checkmark image but I cannot seem to find it. This will probably take far more time and effort than is warranted.

I understand this may prove less than visually appealing for customer applications, but as volunteers on this it is time I doubt anyone will want to invest.

Anyone else want to take a shot at figuring out what is happening?

**Comment by trob** [comment]
I have a solution. Just let me do some tests.

**Comment by skurvish** [comment]
I will be interested to know what you find.

**Comment by trob** [comment]
https://github.com/joomlahenk/fabrik/pull/502

**Comment by wezetel** [comment]
Works like a charm! Thank you
