### ISSUE TITLE
Issue with GitHub

### ISSUE THREAD

**Issue by joomlahenk** [joomlahenk/fabrik#50]
I am trying to get my GHdesktop in sync with GH web. I expected that a pull would, but no. The I did a download .zip and copied this to the GHdesktop. That gave me all files changed, so I discard all files, but still 77 files remain and can't be discarded (lock files). How to recover?

**Comment by skurvish** [comment]
you can do a git reset --hard should reset everything back to the head of the local branch. Then do a pull.

**Comment by joomlahenk** [comment]
I don't have a reset on the GHdesktop

**Comment by skurvish** [comment]
Can't help you then. Maybe Troester can help. I do all my work on a linux system so use the command line for most of my git stuff. Do you have the command line access under windows? If so you may be able to run the reset from there.

**Comment by trob** [comment]
I'm working with GitGui locally, where I can do such resets with a context menu (I think it's not the newest tool but now I'm used to it).
I tried GHdesktop but get lost because I didn't get what was working on my local code and and what on the remote site.

There's a "rebase current branch" in the "Branch" tab and a "Open in command prompt" in the Repository tab (where you should be able to run git reset --hard as command line).
But I have no idea what will happen then exactly.

**Comment by joomlahenk** [comment]
Looks like this was working (don't trust it yet). Checked some files ok.
